chore(ci): fix duplicate parser declaration
This breaks using Python 3.11 with:

argparse.ArgumentError: argument command: conflicting subparser: lint