fix(deps): bump internal packages to latest matching version via yarn upgrade
Fixes the following issue due to conflicting babel version:

  TypeError: Cannot read property 'range' of null

See: https://github.com/babel/babel-eslint/issues/681