fix(tests): normalize test Uint8Array creation
Use `new TypedArray(object)` instead of `TypedArray.from(arrayLike)`.

The reason is that Safari < 14.0 shipped with a broken version of the latter form.
Error encountered:

  TypeError: TypedArray.from requires its this argument subclass a TypedArray constructor

This issue (seemingly fixed in Safari 14+) is not reported on MDN with claims that Safari
has full support since version 10, see:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

It seems we already hit that kind of error, since we have that kind of code in multiple places:

```js
const buffer = new Uint8Array(Array.from(arrayLike, mapFn));

// instead of
const buffer = Uint8Array.from(arrayLike, mapFn);
```