feat(datastore): forward underlying error message to the wrapping error
This makes some errors debuggable, e.g. when using Firefox in private
browsing mode, we would now have an error message (instead of empty string):

OpenFailedError: InvalidStateError A mutation operation was attempted on a database that did not allow mutations.

Also simplify the interface of internal database errors.